postgresql:
  image: registry.ovyka.com/postgresql
  ports:
    - "127.0.0.1:5432:5432"
  volumes:
    - /ovyka/postgresql/data:/data
    - /ovyka/postgresql/log:/var/log/postgresql
  environment:
    DBUSER: pgroot
    DBPASS: pgrootpass
    DB: atlassian
ovykaconfig:
  image: registry.ovyka.com/ovyka-crucible-config
crucibledata:
  image: registry.ovyka.com/crucible-data
  volumes:
    - /ovyka/crucible/data:/opt/atlassian/crucible/data
crucible:
  image: registry.ovyka.com/crucible
  ports:
    - "127.0.0.1:8060:8060"
  volumes_from:
    - crucibledata
    - ovykaconfig
  links:
    - postgresql:db

